# -*- coding: utf-8 -*-
"""Josia Given Santoso - 36230035 - Pemrograman Python UTS

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SNp7neGoH46ZZghnw9ZkrnK43-Sf905R

Ujian Tengah Semester 2

1.   Nama          : Josia Given Santoso
2.   Kelas         : 2PDS1
3.   Tanggal       : 26 Maret 2024
4.   Mata Kuliah   : Bahasa Pemrograman Python

1. Jelaskan 4 struktur data didalam python beserta contohnya, yaitu
*   List
*   Tuple
*   Dictionary
*   Sets

Jawab

- List merupakan struktur data yang nilai atau koleksi didalam nya bisa diubah  secara langsung oleh pengguna.
List dapat menyimpan beberapa tipe data seperti
a) string
b) integer
c) boolean
d) nested list
e) nested tuple

- Tuple merupakan struktur data yang isi nya tidak dapat dirubah oleh pengguna ketika sudah dibuat. Tuple juga bersifat terstuktur dan terurut. Tuple didefinisikan sama seperti list.

- Dictionary merupakan struktur data python yang memungkinkan tipe data tersebut berisi suatu kunci yang memiliki nilai (Key dan Value)

- Set merupakan struktur data yang berisi nilai tetap. Nilai dalam sets tidak boleh ada duplikat dan harus merupakan nilai yang urut. Set digunakan untuk menyimpan koleksi nilai dari tipe data lain seperti list, tuple dan sebagai nya.
"""

list_buah           = ["apel", "mangga", "Jambu", "klengkeng"]

tuple_nama_siswa    = ("Joko", "Udin", "Saepudin", "Bambang")
a, b, c, d = tuple_nama_siswa
print("\n=============================\n")
print("Nama Siswa yang terdapat dalam Tuple adalah", tuple_nama_siswa)

print(a)
print(b)
print(c)
print(c)

dictionary_ID_siswa = {'Joko': 1542, 'Udin': 256, 'Saepudin': 144, 'Bambang': '357' }
set_nomor_urut      = {1, 2, 3, 4}

print("\n=============================\n")
print("Nama Buah-buahan yang terdapat dalam list adalah", list_buah)

print("\n=============================\n")
print("Nama Key dan Value yang terdapat dalam Dictionary adalah", dictionary_ID_siswa)

print("Nama dan ID Siswa", ['Joko'], "adalah")
print("\n=============================\n")

print("Urutan dalam set yang dibuat adalah ", set_nomor_urut)
print("\n=============================\n")

"""2."""

# Mengimport library yang dibutuhkan untuk proyek ini
import pandas as pd
import seaborn as sns
import numpy as np

import matplotlib
from matplotlib import pyplot as plt

#Digunakan untuk mencetak ouput dengan lebih rapi
from IPython.display import display

#2.1 Data Exploration

#Mengambil URL dari dataset csv yang disediakan
url = "https://raw.githubusercontent.com/itsmecevi/dataset/main/cardataset_small.csv"

# Menggunakan pandas untuk membaca dataset dari url dengan format CSV
df = pd.read_csv(url)

# Mencetak hanya 3 baris data pertama dari dataframe
df.head(3)

# Memberikan ringkasan secara langsung tiap kolom
df.describe()

# Membersihkan nilai yang hilang
df = df.dropna()

### Melakukan standarisi kolom, berfungsi agar dataframe tersebut memiliki standar yang konsisten.
df.columns = df.columns.str.lower().str.replace(' ', '_') # Mengganti nilai data kosong dengan "-" khusus tipe data String
string_columns = list(df.dtypes[df.dtypes == 'object'].index)
for col in string_columns:
    df[col] = df[col].str.lower().str.replace(' ', '_')

print("Nilai rata=-rata kolom MSRP adalah :", df['msrp'].mean()) # Mengitung Nilai Rata rata
print("Nilai Median kolom MSRP adalah :", df['msrp'].median()) # Mengitung Nilai Tengah
print("Nilai Maksimum kolom MSRP adalah :", df['msrp'].max()) # Mengitung Nilai Maksimum
print("Nilai Minimum kolom MSRP adalah :", df['msrp'].min()) # Mengitung Nilai Minimum
print("Modus kolom MSRP adalah :", df['msrp'].mode()) # Mengitung Nilai Modus

"""
**Soal Nomor 2.2 Filtering and Selection**
"""

"""

Soal Nomor 2.2 Filtering and Selection

"""
### Melihat ada berapa nilai Unik dari kolom X (model)
jumlah_unique = df['model'].nunique()
print("Jumlah unique values dari column X:", jumlah_unique)
print("\n=============================\n")
print()

### Menampilkan mobil dengan model Civic
kriteria_x = df[(df['model'] == 'civic')] #
display(kriteria_x)

print("\n=============================\n")

### Menampilkan harga MSRP lebih dari 50000
X2 = 50000 # Kriteria nilai MSRP yang tertera pada soal.
print("Data mobil dengan MSRP lebih dari", "$",X2, "adalah:")
print("\n=============================\n")
display(df[df['msrp'] > X2])
print()

### Menampilkan mobil dengan 4 silinder dan 4 pintu
kriteria_khusus = df[(df['engine_cylinders'] == 4.0) & (df['number_of_doors'] == 4.0)] # Menentukan dua kriteria khusus yang harus terpenuhi
print("\n=============================\n")
display(kriteria_khusus)

"""**Soal Nomor 2.3 Data Manipulation**"""

"""

Soal Nomor 2.3 Data Manipulation

"""

#### Menghitung efisiensi bahan Bakar (MPG). Berdasarkan hasil rata rata City_MPG dan Highway_MPG
print("\n=============================\n")
df['Efisiensi_MPG_rata_rata'] = (df['city_mpg'] + df['highway_mpg']) / 2
print("Kolom 'Efisiensi_MPG_rata_rata' berhasil ditambahkan.")

### Mengubah nama kolom "Engine HP" menjadi "Horsepower"
print("\n=============================\n")
df.rename(columns={'engine_hp': 'horsepower'}, inplace=True) # Mengunakan fungsi rename untuk mengubah nama kolom
print("Nama kolom 'engine_hp' telah diganti menjadi 'horsepower' ")

### Menghapus kolom "Market Category" menggunakan metode Drop
print("\n=============================\n")
df.drop(columns='market_category', inplace=True) # Mengunakan fungsi drop untuk menghapus kolom
print("Nama kolom 'market category' telah dihapus")
print("=============================\n")
print()

# Mencetak semua perubahan yang telah dibuat sebagai dataframe
print("Menampilkan hasil akhir perubahan dataframe yang telah dibuat")
print("\n=============================\n")
display(df)

"""**Soal Nomor 2.4 Statistical Analysis**"""

"""

Soal Nomor 2.4 Statistical Analysis

"""
# Menghitung korelasi antara kolom "engine HP" yang sudah diubah menjadi horsepower, dengan MSRP
display("Korelasi")
korelasi = df['msrp'].corr(df['horsepower'])
print("Korelasi antara kolom Horsepower dan MSRP adalah ':", korelasi)
print("\n=============================\n")

# Menghitung jumlah nilai unik mobil dengan tipe transmisi yang berbeda
display("Nilai Unik")
jumlah_unik_transmisi = df['transmission_type'].nunique()
print("Jumlah unique values dari Tipe transmisi mobil adalah :", jumlah_unique)
print("\n=============================\n")

# Menghitung rata rata dan median dari kolom "Popularity"
print("Nilai rata-rata kolom Popularity adalah :", df['msrp'].mean()) #Mengitung Nilai Rata rata
print("Nilai Median kolom Popularity adalah :", df['msrp'].median()) #Mengitung Nilai Tengah

"""**Soal Nomor 2.5 Data Visualization**"""

"""

Soal Nomor 2.5 Data Visualization

"""

# Membuat histogram untuk kolom 'Engine HP' yang sudah di ubah namanya menjadi kolom 'Horsepower'
plt.figure(figsize=(6, 4)) # Menentukan ukuran dari figure yang akan dibuat
sns.histplot(df.horsepower, bins=40, color='blue', alpha=1) # Menggunakan kolom horsepower dan mengganti warna figure.
plt.ylabel('Frequency') # Sumbu Y adalah frekuensi
plt.xlabel('Horsepower') # Sumbu X adalah nilai dari Horsepower
plt.title('Distribution of Horsepower')

plt.show()

# Membuat scatterplot untuk menampilkan hubungan antar highway MPG dan City MPG
plt.figure(figsize=(6, 4))
plt.scatter(df['city_mpg'], df['highway_mpg'], color='blue')
plt.xlabel('Harga (X)')
plt.ylabel('City MPG (Y)')
plt.title('Scatter Plot Hubungan Harga dan City MPG')
plt.tight_layout()

plt.show()

# Membuat barplot untuk menampilkan jumlah mobil berdasarkan Ukuran Kendaraan "Vehicle Size"
plt.figure(figsize=(6, 4))
sns.histplot(df.vehicle_size, bins=40, color='blue', alpha=1)
plt.ylabel('Frequency')
plt.xlabel('Vehicle Size')
plt.title('Distribution of Vehicle Size')

plt.show()

"""**Soal Nomor 3 Upload Hasil UTS ke Email dosen dan kaggle**"""